spring:
  jpa:
    properties:
      hibernate.format_sql: true
      hibernate.hbm2ddl: update
      hibernate.show_sql: true
      hibernate.generate_ddl: false
      hibernate.open_in_view: false
  account-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/account?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      leak-detection-threshold: 5000
  user-datasource:
    jdbc-url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
